INSERT INTO client_categories (name, description, created_at, updated_at) VALUES
('Technology', 'Products and services related to tech devices and software', NOW(), NOW()),
('Healthcare', 'Medical and healthcare-related products and services', NOW(), NOW()),
('Automotive', 'Vehicles and automotive services', NOW(), NOW()),
('Real Estate', 'Real estate buying, selling, and rental services', NOW(), NOW()),
('Fashion', 'Clothing, accessories, and fashion-related products', NOW(), NOW()),
('Food & Beverage', 'Restaurants, food delivery, and catering services', NOW(), NOW()),
('Education', 'Educational institutions, online courses, and training programs', NOW(), NOW()),
('Finance', 'Financial services, banking, and investment products', NOW(), NOW()),
('Travel', 'Travel agencies, airlines, and tour operators', NOW(), NOW()),
('Fitness', 'Gyms, fitness equipment, and health services', NOW(), NOW()),
('Hospitality', 'Hotels, resorts, and accommodation services', NOW(), NOW()),
('Entertainment', 'Movies, music, and entertainment services', NOW(), NOW()),
('Retail', 'Retail stores and e-commerce services', NOW(), NOW()),
('Consulting', 'Business consulting and advisory services', NOW(), NOW()),
('Legal', 'Legal services and law firms', NOW(), NOW()),
('Insurance', 'Insurance services for health, vehicles, and life', NOW(), NOW()),
('Construction', 'Construction companies and contractors', NOW(), NOW()),
('Agriculture', 'Agriculture, farming, and livestock-related services', NOW(), NOW()),
('Beauty & Cosmetics', 'Cosmetics, skincare, and beauty-related products', NOW(), NOW()),
('Nonprofit', 'Non-governmental organizations and charities', NOW(), NOW()),
('Logistics', 'Shipping, transportation, and logistics services', NOW(), NOW()),
('Telecommunications', 'Telecom services, internet, and mobile providers', NOW(), NOW()),
('Pharmaceutical', 'Pharmacy and pharmaceutical product providers', NOW(), NOW()),
('Energy', 'Energy suppliers, solar power, and electricity services', NOW(), NOW()),
('Sports', 'Sports equipment and services related to athletics', NOW(), NOW()),
('Art & Design', 'Art galleries, design services, and creative industries', NOW(), NOW()),
('Manufacturing', 'Manufacturing and production companies', NOW(), NOW()),
('Media', 'Media companies, advertising, and public relations services', NOW(), NOW()),
('Pet Services', 'Pet care, grooming, and veterinary services', NOW(), NOW()),
('Home Improvement', 'Home renovation, repair, and improvement services', NOW(), NOW());
