INSERT INTO device_types(created_at, updated_at, name, description) VALUES
(NOW(), NOW(), 'Teltonika FMB920', 'Compact GPS tracker with Bluetooth and internal backup battery'),
(NOW(), NOW(), 'Teltonika FMB120', 'Vehicle GPS tracker with RS232/RS485 data interface support'),
(NOW(), NOW(), 'Teltonika TMT250', 'Personal GPS tracker with a panic button and waterproof casing'),
(NOW(), NOW(), 'Teltonika FMB001', 'Plug-and-play OBDII GPS tracker for real-time vehicle monitoring'),
(NOW(), NOW(), 'Ruptela FM-Eco4+', 'Basic vehicle tracker with internal GNSS/GSM antennas'),
(NOW(), NOW(), 'Ruptela FM-Pro4', 'Advanced vehicle tracker with CAN data reading for fleet management'),
(NOW(), NOW(), 'Ruptela FM-Tco4 HCV', 'Heavy-duty vehicle tracker with tachograph data reading support'),
(NOW(), NOW(), 'Ruptela FM-Eco4 T', 'GPS tracker with temperature sensor support for cold chain logistics'),
(NOW(), NOW(), 'Queclink GV55', 'Mini GPS tracker for asset tracking with multiple I/O interfaces'),
(NOW(), NOW(), 'Queclink GL300', 'Personal and asset tracker with extended battery life and waterproof casing'),
(NOW(), NOW(), 'Queclink GV300', 'Fleet management GPS tracker with ignition detection and driver behavior monitoring'),
(NOW(), NOW(), 'Concox GT06N', 'Affordable GPS tracker with multiple alarms and real-time tracking'),
(NOW(), NOW(), 'Concox AT1', 'Magnetic GPS tracker with a large battery for long-term asset tracking'),
(NOW(), NOW(), 'Concox JM-LG01', 'Waterproof GPS tracker designed for motorcycles and electric scooters'),
(NOW(), NOW(), 'Suntech ST3300', 'GPS tracker for vehicle fleet management with fuel monitoring capability'),
(NOW(), NOW(), 'Suntech ST3940', 'Advanced vehicle tracker with CAN bus data reading and harsh driving detection'),
(NOW(), NOW(), 'Meitrack T366', 'Waterproof GPS tracker with multiple alarms and real-time positioning for fleet management'),
(NOW(), NOW(), 'Meitrack T622', 'Professional GPS tracker with RFID reader support and fuel consumption monitoring'),
(NOW(), NOW(), 'Meitrack MVT600', 'Vehicle tracker with fuel level monitoring and driver behavior analysis'),
(NOW(), NOW(), 'CalAmp LMU-3030', 'OBDII plug-in GPS tracker for real-time vehicle diagnostics and tracking');
